services:
  php:
    build:
      context: ./
      dockerfile: ./php.Dockerfile
    volumes:
      - ./wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./index.php:/var/www/index.php
      - ./wp-cli.yml:/var/www/wp-cli.yml
      - ./install-wp.sh:/var/www/install-wp.sh
    env_file:
      - .env
    depends_on:
      - db
      - phpmyadmin
    restart: always
    ports:
      - 8080:80

  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    restart: always

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8100:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 64M

volumes:
  db_data:
